name: API CI
#on: [push] # si no fuera un monorepo se podria hacer de esta forma
on:
  push:
    paths:
      - "./api/**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json # esto tampoco fuera necesario si no fuera un monorepo
      - name: install
        shell: bash
        run: npm ci
      - name: run unit test
        shell: bash
        run: npm run test